# Generated by Django 3.2 on 2023-01-10 12:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('new_film', 'New Film'), ('new_user', 'New User'), ('review_like', 'Review Like')], max_length=15)),
                ('content', models.JSONField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('last_notification_send', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('communication_method', models.CharField(choices=[('ws', 'Ws'), ('email', 'Email'), ('telegram', 'Telegram')], max_length=15)),
                ('allow_communication', models.BooleanField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_notification_send_to_user', models.DateTimeField(null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.user')),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
    ]
