version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: nots_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    env_file:
      - .env
    healthcheck:
      test: nc -z localhost 5672 || exit -1
      interval: 5s
      timeout: 10s
      retries: 10
    restart: always

  postgres:
    image: postgres:13.3
    container_name: nots_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 10s
      retries: 10

  fastapi:
    build:
      context: .
      args:
        PROJECT_ENV: produdction
    image: project_image:latest
    container_name: nots_fastapi
    entrypoint: sh -c "app/src/entrypoint.sh"
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: on-failure

  django:
    image: project_image:latest
    container_name: nots_django
    entrypoint: sh -c "admin_panel/src/entrypoint.sh"
    depends_on:
      - fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: on-failure

volumes:
  rabbitmq_data:
  postgres_data: