version: '3.9'

services:
  rabbit_worker:
    build:
      context: services/sender
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: >
      bash -c "python -m v1.workers.rabbit_worker"


  websocket_worker:
    build:
      context: services/sender
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8765:8765"
    env_file:
      - .env
    command: >
      bash -c "python -m v1.workers.websocket_worker --port 8765 --ip 0.0.0.0"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:
  postgres_data:
  static:
  media:

