version: '3.9'

services:
  rabbit_worker:
    build:
      context: sender
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    env_file:
      - .env
    command: >
      bash -c "python -m v1.workers.rabbit_worker"

  websocket_worker:
    build:
      context: sender
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8765:8765"
    env_file:
      - .env
    command: >
      bash -c "python -m v1.workers.websocket_worker --port 8765 --ip 0.0.0.0"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    env_file:
      - .env

volumes:
  rabbitmq_data:
  postgres_data:
  static:
  media:

