version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine3.17
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${DJANGO_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DJANGO_POSTGRES_USER}
      POSTGRES_DB: ${DJANGO_POSTGRES_DB}
    env_file:
      .env

  admin-panel:
    container_name: admin_panel
    build:
      context: services/admin_panel
      dockerfile: Dockerfile
    volumes:
      - static:/opt/app/static/
      - media:/opt/app/media/
    depends_on:
      - postgres
    env_file:
      - .env
    command: >
      bash -c "python manage.py collectstatic --noinput
      && python manage.py compilemessages
      && uwsgi --strict --ini uwsgi/uwsgi.ini"

  celery:
    container_name: celery
    build:
      context: services/admin_panel
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    command: celery -A admin_panel worker -l info

  celery-beat:
    container_name: celery_beat
    build:
      context: services/admin_panel
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    command: celery -A admin_panel beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler

  api:
    build: ./services/notific_api
    container_name: api_notifications
    entrypoint: >
      sh -c "gunicorn --bind :8000 --workers $GUNICORN_WORKERS --threads $GUNICORN_THREADS main:app \
                      --worker-class uvicorn.workers.UvicornH11Worker --preload --timeout $GUNICORN_TIMEOUT"
    volumes:
      - api_data:/data
    env_file:
      - .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    env_file:
      - .env

volumes:
  rabbitmq_data:
  postgres_data:
  static:
  media:
  api_data:


