@startuml
skinparam actorStyle awesome
actor User as User
actor Manager as Manager

rectangle "Notification" as Notification {
	component "API" as API
	component "DB" as DB
	component "Панель \n администратора" as Admin_panel

    rectangle "Broker" as Broker {
    component "Точка обмена " as exchange
    component "Очередь \n лайков" as queue_social_activity
    component "Очередь \n welcome \n писем" as queue_welcome_message
    component "Очередь \n новых серий " as queue_new_episode
    }
    rectangle "Генераторы" as generators {
    component "Лайки \n пользователей" as generators_1

    }
	rectangle "Workers" as Workers {
    component "Обработчик \n сообщений о \n лайках" as social_activity
    component "Обработчик \n сообщений о \n новых сериях" as new_episode
    component "Обработчик \n сообщений о \n приветствиях" as welcome_message
    }
}

User --> API
Manager --> Admin_panel
Admin_panel -> API

API --> DB
Workers --> DB
generators -> DB
API --> exchange
generators_1 --> exchange
exchange --> queue_social_activity
exchange --> queue_new_episode
exchange --> queue_welcome_message
queue_social_activity --> social_activity
queue_new_episode --> new_episode
queue_welcome_message --> welcome_message

@enduml