"""empty message

Revision ID: 57b0e325c8c0
Revises:
Create Date: 2023-03-14 18:44:15.893861

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57b0e325c8c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'short_url',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('original_url', sa.String(length=500), nullable=False),
        sa.Column('short_id', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('short_id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_url')
    # ### end Alembic commands ###
