# Generated by Django 4.1.7 on 2023-03-03 12:29
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[str] = []

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('template_content', models.TextField(blank=True, verbose_name='template_content')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
