# cat 0001_initial.py
# Generated by Django 4.2 on 2023-04-06 13:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ReviewInfo',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movie_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('author_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('review_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('likes_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['review_id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewStorage',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_id', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'ordering': ['review_id'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('welcome_message', 'Welcome'),
                            ('new_content', 'New Content'),
                            ('new_likes', 'New Likes'),
                            ('promo', 'Promo'),
                        ],
                        default='new_content',
                        max_length=255,
                    ),
                ),
                ('subject', models.TextField(default='', max_length=255, verbose_name='subject')),
                ('template_files', models.FilePathField(allow_files=False, allow_folders=True, path='templates/')),
                ('text_msg', models.TextField(blank=True, default='', max_length=4096)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('welcome_message', 'Welcome'),
                            ('new_content', 'New Content'),
                            ('new_likes', 'New Likes'),
                            ('promo', 'Promo'),
                        ],
                        default='new_content',
                        max_length=255,
                    ),
                ),
                (
                    'user_group',
                    models.CharField(
                        choices=[
                            ('all', 'All User'),
                            ('group_1', 'Group 1'),
                            ('group_2', 'Group 2'),
                            ('group_3', 'Group 3'),
                            ('group_4', 'Group 4'),
                        ],
                        default='all',
                        max_length=255,
                    ),
                ),
                ('movie_id', models.CharField(blank=True, default='', max_length=255)),
                ('text_to_promo', models.CharField(blank=True, default='', max_length=4096)),
                (
                    'template_pkid',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.template'),
                ),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
