# Generated by Django 4.1.7 on 2023-03-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_template_template_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='template_content',
        ),
        migrations.RemoveField(
            model_name='template',
            name='template_short_description',
        ),
        migrations.AddField(
            model_name='template',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('welcome_message', 'Welcome'),
                    ('new_content', 'New Content'),
                    ('new_likes', 'New Likes'),
                    ('promo', 'Promo'),
                ],
                default='new_content',
                max_length=255,
                verbose_name='event_type',
            ),
        ),
        migrations.AddField(
            model_name='template',
            name='subject',
            field=models.CharField(default='', max_length=255, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='template',
            name='text_msg',
            field=models.TextField(blank=True, default='', max_length=4096, verbose_name='text_msg'),
        ),
        migrations.AddField(
            model_name='template',
            name='text_to_promo',
            field=models.TextField(blank=True, default='', max_length=4096, verbose_name='text_to_promo'),
        ),
        migrations.AddField(
            model_name='template',
            name='user_group',
            field=models.CharField(
                choices=[
                    ('all', 'All User'),
                    ('group_1', 'Group 1'),
                    ('group_2', 'Group 2'),
                    ('group_3', 'Group 3'),
                    ('group_4', 'Group 4'),
                ],
                default='all',
                max_length=255,
                verbose_name='user group',
            ),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_files',
            field=models.FilePathField(
                allow_files=False, allow_folders=True, path='templates/', verbose_name='template_files'
            ),
        ),
    ]
