# Generated by Django 4.1.7 on 2023-03-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_template_template_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_short_description',
            field=models.TextField(verbose_name='template_short_description'),
        ),
    ]
