# Generated by Django 4.1.7 on 2023-03-16 18:32
from typing import Any

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_template_template_content_and_more'),
        ('notifications', '0006_alter_template_template_short_description'),
    ]

    operation: list[Any] = []
