# Generated by Django 4.1.7 on 2023-03-18 19:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_merge_20230316_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewInfo',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movie_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('author_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('review_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('likes_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['review_id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewStorage',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_id', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'ordering': ['review_id'],
            },
        ),
        migrations.RemoveField(
            model_name='template',
            name='text_to_promo',
        ),
        migrations.RemoveField(
            model_name='template',
            name='user_group',
        ),
        migrations.AlterField(
            model_name='template',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('welcome_message', 'Welcome'),
                    ('new_content', 'New Content'),
                    ('new_likes', 'New Likes'),
                    ('promo', 'Promo'),
                ],
                default='new_content',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='template',
            name='subject',
            field=models.TextField(default='', max_length=255, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_files',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='templates/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='text_msg',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('welcome_message', 'Welcome'),
                            ('new_content', 'New Content'),
                            ('new_likes', 'New Likes'),
                            ('promo', 'Promo'),
                        ],
                        default='new_content',
                        max_length=255,
                    ),
                ),
                (
                    'user_group',
                    models.CharField(
                        choices=[
                            ('all', 'All User'),
                            ('group_1', 'Group 1'),
                            ('group_2', 'Group 2'),
                            ('group_3', 'Group 3'),
                            ('group_4', 'Group 4'),
                        ],
                        default='all',
                        max_length=255,
                    ),
                ),
                ('movie_id', models.CharField(blank=True, default='', max_length=255)),
                ('text_to_promo', models.CharField(blank=True, default='', max_length=4096)),
                (
                    'template_pkid',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.template'),
                ),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
